 function val = Drive_to_Power(M)
    DC=M; % M is in mph, and is a table, with first column as t, second as mph
    rho = 1.1455;
    Cd = 10;
    A = 7.7;
    m =6600;
    g=9.81;
    eff_mot = .85;
    DC = table2array(DC);
    time = DC([1:end-1],1);
    velocities = DC([1:end],2)/2.2369;
    accel = diff(velocities);
    velocities = velocities ([1:end-1]);
    F_fric = 0.03*m*g*velocities;
    F_drag = 0.5*rho*Cd*A*velocities.^2;
    Fm = m*accel+F_drag + F_fric;
    Pm=Fm.*velocities/eff_mot;
    Pm = [time,Pm];
    Pm = Pm([1010:1370],2);
    val=Pm;
 end